
all: task1 task2

task1: task1.c
	gcc task1.c function.c -o task1

task2: task2.c
	gcc task2.c function.c -o task2

task3: task3.c
	gcc task3.c function.c -o task3

task4: task4.c
	gcc task4.c function.c -o task4

clean:
	rm -f task1 task2 
